name: Release Production apk
on:
  workflow_dispatch:
    inputs:
      version:
        description: Bump version
        required: false
        default: 1.0.0

  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - dev
      - release
    types:
      - opened
      - reopened
      - synchronize

jobs:
  build:
    name: Build & Deploy a release APK
    env:
      APP_NAME: "Pexza App"
      GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      RELEASE_TYPE: patch
      # BUMP_TAG:
      # BUMP_VERSION:
    runs-on: ubuntu-latest
    outputs:
      bump_tag: ${{ env.BUMP_TAG }}
      bump_tag_version: ${{ env.BUMP_VERSION }}
    steps:
      - name: Fetch Repo HEAD
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # - name: Set up Java Environment
      #   uses: actions/setup-java@v1
      #   with:
      #     java-version: 1.8

      # - name: Install NDK
      #   if: steps.ndk_cache.outputs.cache-hit != 'true'
      #   run: echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;21.0.6113669" --sdk_root=${ANDROID_SDK_ROOT}

      # - name: Set up Flutter Environment
      #   uses: subosito/flutter-action@v1
      #   with:
      #     flutter-version: "1.25.0-8.3.pre"
      #     channel: "beta"

      # - name: Run Pre-build scipts
      #   run: |
      #     flutter pub get
      #     # flutter test

      # - name: Build Flutter Apk
      #   run: |
      #     flutter build apk -t lib/main.dart --release --target-platform android-arm,android-arm64 --split-per-abi --flavor=prod --obfuscate --split-debug-info=./build/app/outputs/apk/obfuscation --dart-define=BUILD_NUMBER=$BUILD_NUMBER --dart-define=BUILD_VERSION=$BUILD_VERSION --dart-define=BUILD_COMMIT=$FCI_COMMIT

      - name: Bump version and push tag
        id: bump_tag
        if: ${{ github.event.inputs.version == '' }}
        uses: mathieudutour/github-tag-action@v4.5
        with:
          release_branches: .*
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Environment variables
        run: |
          echo "BUMP_TAG=${{ steps.bump_tag.outputs.new_tag }}" >> $GITHUB_ENV
          echo "BUMP_VERSION=${{ steps.bump_tag.outputs.new_version }}" >> $GITHUB_ENV

      # - name: Push APK to Release Tags
      #   uses: ncipollo/release-action@v1
      #   with:
      #     artifacts: "build/app/outputs/apk/prod/release/*.apk,build/app/outputs/apk/release/*.apk,build/app/outputs/apk/*"
      #     name: ${{ env.APP_NAME }}-${{ env.BUMP_VERSION }}
      #     tag: ${{ env.BUMP_TAG }}
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     allowUpdates: true
      #     omitName: false
      #     omitBody: false

  notify:
    runs-on: ubuntu-latest
    needs: build
    env:
      APP_NAME: "Pexza App"
      REPOSITORY_NAME: "pexza-app"
      API_KEY: ${{ secrets.ZAPIER_TEAM_API_KEY }}
    steps:
      - name: Test workflow_dispatch
        run: |
          echo "New Tag = ${{ needs.build.outputs.bump_tag }}"
          echo "Version = ${{ needs.build.outputs.bump_tag_version }}"
      # - name: Send Push Notification
      #   uses: techulus/push-github-action@1.0.0
      #   env:
      #     API_KEY: ${{ env.API_KEY }}
      #     TITLE: Version Bump Notification
      #     MESSAGE: Bump Version ${{ needs.build.outputs.bump_tag_version }} available for download at https://github.com/f0rx/${{ env.REPOSITORY_NAME }}/releases/tag/${{ needs.build.outputs.bump_tag }}
      #     LINK: https://github.com/f0rx/${{ env.REPOSITORY_NAME }}/releases/tag/${{ needs.build.outputs.bump_tag }}
