name: Release Production apk
on:
  workflow_dispatch:
    inputs:
      version:
        description: Bump version
        required: true
        default: 1.0.0

  push:
    branches:
      - main
      - release
      - dev
  pull_request:
    branches:
      - main
      - release
    types:
      - opened
      - reopened
      - closed
      - synchronize
      - closed

jobs:
  build:
    name: Build & Deploy Production APK
    runs-on: ubuntu-latest
    env:
      APP_NAME: "Pexza App"
      GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      RELEASE_TYPE: patch
      FLUTTER_VERSION: "1.25.0-8.3.pre"
    outputs:
      bump_tag: ${{ env.BUMP_TAG }}
      bump_tag_version: ${{ env.BUMP_VERSION }}
      release_url: ${{ env.RELEASE_URL }}
      changelog: ${{ env.CHANGE_LOG }}
    steps:
      - name: Fetch Repo HEAD
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Java Environment
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Prepare NDK dir for caching
        run: |
          sudo mkdir -p /usr/local/lib/android/sdk/ndk
          sudo chmod -R 777 /usr/local/lib/android/sdk/ndk
          sudo chown -R $USER:$USER /usr/local/lib/android/sdk/ndk

      - name: Cache Android NDK
        id: ndk-cache
        uses: actions/cache@v2
        with:
          path: /usr/local/lib/android/sdk/ndk
          key: ndk-cache-21.0.6113669-v2

      - name: Install NDK
        if: steps.ndk-cache.outputs.cache-hit != 'true'
        run: echo "y" | sudo ${ANDROID_SDK_ROOT}/tools/bin/sdkmanager --install "ndk;21.0.6113669"

      - name: Cache Flutter dependencies
        uses: actions/cache@v2
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.OS }}-flutter-install-cache-${{ env.FLUTTER_VERSION }}

      - name: Set up Flutter Environment
        uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: "beta"

      - name: Run Pre-build scipts
        run: |
          flutter pub get
          # flutter test

      - name: Build Flutter Apk
        run: |
          flutter build apk -t lib/main.dart --release --target-platform android-arm,android-arm64 --split-per-abi --flavor=prod --obfuscate --split-debug-info=./build/app/outputs/apk/obfuscation --dart-define=BUILD_NUMBER=$BUILD_NUMBER --dart-define=BUILD_VERSION=$BUILD_VERSION --dart-define=BUILD_COMMIT=$FCI_COMMIT

      - name: Bump version and push tag
        id: bump_tag
        if: ${{ github.event.inputs.version == '' }}
        uses: mathieudutour/github-tag-action@v4.5
        with:
          release_branches: .*
          create_annotated_tag: true
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Environment variables
        run: |
          if ${{ github.event.inputs.version == '' }}; then
            echo "BUMP_TAG=${{ steps.bump_tag.outputs.new_tag }}" >> $GITHUB_ENV
            echo "BUMP_VERSION=${{ steps.bump_tag.outputs.new_version }}" >> $GITHUB_ENV
            echo "CHANGE_LOG=${{ steps.bump_tag.outputs.changelog }}" >> $GITHUB_ENV
          else
            echo "BUMP_TAG=v${{ github.event.inputs.version}}" >> $GITHUB_ENV
            echo "BUMP_VERSION=${{ github.event.inputs.version}}" >> $GITHUB_ENV
            echo "CHANGE_LOG=Custom Workflow dispatch. Please check repo for changelog." >> $GITHUB_ENV
          fi

      - name: Push APK to Release Tags
        id: push_apk_to_tag
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/*.apk,build/app/outputs/apk/obfuscation/*"
          name: ${{ env.APP_NAME }}-${{ env.BUMP_VERSION }}
          tag: ${{ env.BUMP_TAG }}
          token: ${{ secrets.GITHUB_TOKEN }}
          body: ${{ env.CHANGE_LOG }}
          allowUpdates: false
          omitName: false
          omitBody: false
          replacesArtifacts: false
          artifactErrorsFailBuild: false

      - name: Post Action "Push APK to release Tags"
        run: |
          echo ${{ steps.push_apk_to_tag.outputs.id }}
          echo ${{ steps.push_apk_to_tag.outputs.html_url }}
          echo ${{ steps.push_apk_to_tag.outputs.upload_url }}
          echo "RELEASE_URL=${{ steps.push_apk_to_tag.outputs.html_url }}" >> $GITHUB_ENV

  notify:
    runs-on: ubuntu-latest
    needs: build
    env:
      APP_NAME: "Pexza App"
      REPOSITORY_NAME: "pexza-app"
      API_KEY: ${{ secrets.ZAPIER_TEAM_API_KEY }}
    steps:
      - name: Send Push Notification
        uses: techulus/push-github-action@1.0.0
        env:
          API_KEY: ${{ env.API_KEY }}
          TITLE: Version Bump Notification
          MESSAGE: ${{ needs.build.outputs.changelog }}. Download at -> ${{ needs.build.outputs.release_url }}
          LINK: https://github.com/f0rx/${{ env.REPOSITORY_NAME }}/releases/tag/${{ needs.build.outputs.bump_tag }}
